/**
 * Undercover word pairs by language.
 * Each pair: [civilianWord, undercoverWord]
 * 
 * Quality criteria:
 * - Similar but subtly different (not obvious in 1 second)
 * - Relatable to young people / internet culture
 * - Fun to describe and debate
 * - No offensive or insensitive content
 */

export type Difficulty = 'easy' | 'medium' | 'hard';

export interface WordPairEntry {
  pair: [string, string];
  difficulty: Difficulty;
  tags?: string[];  // for future theme packs
}

// Flat pairs for backward compat (pickWordPair uses this)
export const WORD_PAIRS_BY_LANG: Record<string, [string, string][]> = {
  zh: [
    // ===== EASY: 差异明显，新手友好 =====
    ['可口可乐', '百事可乐'],
    ['微博', '微信'],
    ['火锅', '烧烤'],
    ['包子', '饺子'],
    ['奶茶', '果茶'],
    ['高铁', '火车'],
    ['空调', '电风扇'],
    ['洗衣机', '洗碗机'],
    ['耳机', '音响'],
    ['蝴蝶', '蜜蜂'],
    ['钢琴', '吉他'],
    ['直升机', '飞机'],
    ['企鹅', '鸵鸟'],
    ['鳄鱼', '鲨鱼'],
    ['沙漠', '沙滩'],
    ['烤箱', '微波炉'],
    ['雨伞', '雨衣'],
    ['密码', '钥匙'],
    ['双肩包', '行李箱'],
    ['照相机', '望远镜'],

    // ===== MEDIUM: 需要动脑描述 =====
    ['渣男', '海王'],
    ['小鲜肉', '老干部'],
    ['泡面', '螺蛳粉'],
    ['网吧', '电竞酒店'],
    ['双十一', '黑五'],
    ['外卖', '堂食'],
    ['初恋', '暗恋'],
    ['闺蜜', '兄弟'],
    ['相亲', '网恋'],
    ['男朋友', '男闺蜜'],
    ['学霸', '学渣'],
    ['黑客', '程序员'],
    ['微商', '代购'],
    ['熬夜', '通宵'],
    ['结婚', '订婚'],
    ['长城', '故宫'],
    ['薰衣草', '满天星'],
    ['口红', '腮红'],
    ['婚纱', '西服'],
    ['魔术', '杂技'],
    ['算命', '占卜'],
    ['降落伞', '热气球'],
    ['毒药', '解药'],
    ['刺客', '狙击手'],
    ['蜘蛛侠', '蝙蝠侠'],
    ['火锅', '麻辣烫'],
    ['冰淇淋', '雪糕'],
    ['豆浆', '牛奶'],
    ['玫瑰', '康乃馨'],
    ['森林', '草原'],
    ['闪电', '极光'],
    ['刺猬', '仙人掌'],

    // ===== HARD: 微妙差异，高手局 =====
    ['已读不回', '消息撤回'],
    ['社死', '社牛'],
    ['PUA', '舔狗'],
    ['绿茶', '心机'],
    ['恋爱脑', '恋爱酸臭'],
    ['YYDS', '绝绝子'],
    ['内卷', '躺平'],
    ['摸鱼', '划水'],
    ['凡尔赛', '装X'],
    ['种草', '拔草'],
    ['emo', '破防'],
    ['开摆', '摆烂'],
    ['塌房', '翻车'],
    ['打工人', '牛马'],
    ['嗑CP', '磕糖'],
    ['脑补', '脑洞'],
    ['吃瓜', '瓜田'],
    ['白月光', '朱砂痣'],
    ['暧昧', '友达以上'],
    ['备胎', '千斤顶'],
    ['搭子', '饭搭子'],

    // ===== 品牌/IP/流行文化 =====
    ['瑞幸', '星巴克'],
    ['喜茶', '蜜雪冰城'],
    ['抖音', '快手'],
    ['小红书', '知乎'],
    ['B站', '油管'],
    ['淘宝', '拼多多'],
    ['肯德基', '麦当劳'],
    ['王者荣耀', '英雄联盟'],
    ['原神', '崩坏星穹铁道'],
    ['吃鸡', '堡垒之夜'],
    ['周杰伦', '林俊杰'],
    ['哈利波特', '指环王'],
    ['漫威', 'DC'],
    ['海贼王', '火影忍者'],
    ['柯南', '金田一'],
    ['ChatGPT', 'Siri'],
    ['微信支付', '支付宝'],
    ['滴滴', '高德打车'],
    ['美团', '饿了么'],
    ['keep', '刘畊宏'],

    // ===== 美食局 =====
    ['螺蛳粉', '臭豆腐'],
    ['煎饼果子', '手抓饼'],
    ['小龙虾', '大闸蟹'],
    ['烤鸭', '叫花鸡'],
    ['冰糖葫芦', '棉花糖'],
    ['臭豆腐', '榴莲'],
    ['珍珠奶茶', '椰汁'],
    ['糖醋排骨', '红烧肉'],
    ['鸭脖', '鸡爪'],
    ['油条', '麻花'],

    // ===== 恋爱/社交局 =====
    ['前任', '现任'],
    ['异地恋', '网恋'],
    ['表白', '暗示'],
    ['撩人', '撩骚'],
    ['冷暴力', '热暴力'],
    ['直男', '钢铁直男'],
    ['情人节', '七夕'],
    ['单身狗', '恋爱狗'],
    ['AA制', '请客'],
    ['约会', '相亲'],

    // ===== 职场/校园局 =====
    ['期末考试', '高考'],
    ['翘课', '旷工'],
    ['实习', '打工'],
    ['简历', '面试'],
    ['老板', '甲方'],
    ['PPT', 'Excel'],
    ['周报', '日报'],
    ['迟到', '早退'],
    ['食堂', '外卖'],
    ['室友', '同事'],
  ],

  en: [
    // ===== EASY =====
    ['Coke', 'Pepsi'],
    ['Netflix', 'YouTube'],
    ['iPhone', 'Android'],
    ['TikTok', 'Instagram'],
    ["McDonald's", 'Burger King'],
    ['Uber', 'Lyft'],
    ['Marvel', 'DC'],
    ['Pizza', 'Burger'],
    ['Summer', 'Winter'],
    ['Cats', 'Dogs'],
    ['Laptop', 'Tablet'],
    ['Gym', 'Yoga'],
    ['Coffee', 'Energy Drink'],
    ['Helicopter', 'Airplane'],
    ['Umbrella', 'Raincoat'],
    ['Backpack', 'Suitcase'],
    ['Ice Cream', 'Popsicle'],
    ['Desert', 'Beach'],
    ['Penguin', 'Ostrich'],
    ['Crocodile', 'Shark'],

    // ===== MEDIUM =====
    ['Tinder', 'Bumble'],
    ['Millennial', 'Gen Z'],
    ['Influencer', 'Celebrity'],
    ['Podcast', 'Radio'],
    ['Therapist', 'Psychiatrist'],
    ['Introvert', 'Extrovert'],
    ['Startup', 'Cult'],
    ['Vegan', 'Vegetarian'],
    ['Hangover', 'Drunk'],
    ['Robot', 'Cyborg'],
    ['Wizard', 'Witch'],
    ['Vampire', 'Werewolf'],
    ['Ninja', 'Pirate'],
    ['FBI', 'CIA'],
    ['College', 'High School'],
    ['Money', 'Fame'],
    ['Pancake', 'Waffle'],
    ['Pop', 'Rock'],
    ['WiFi', 'Bluetooth'],
    ['Password', 'Key'],
    ['Poison', 'Antidote'],
    ['Castle', 'Villa'],
    ['Prison', 'Asylum'],
    ['Detective', 'Spy'],
    ['Rose', 'Tulip'],

    // ===== HARD =====
    ['Ghosting', 'Breadcrumbing'],
    ['Gaslighting', 'Love Bombing'],
    ['Situationship', 'Friends with Benefits'],
    ['Red Flag', 'Green Flag'],
    ['Main Character Energy', 'NPC Energy'],
    ['Touch Grass', 'Go Outside'],
    ['Doomscrolling', 'Binge Watching'],
    ['Quiet Quitting', 'Quiet Firing'],
    ['Side Hustle', 'Passion Project'],
    ['FOMO', 'JOMO'],
    ['Cancel Culture', 'Call Out Culture'],
    ['Mansplaining', 'Gaslighting'],
    ['Hot Take', 'Unpopular Opinion'],
    ['Rizz', 'Charisma'],
    ['Slay', 'Serve'],
    ['No Cap', 'For Real'],
    ['Sus', 'Shady'],
    ['Simp', 'Simu'],
    ['Toxic', 'Problematic'],
    ['Bestie', 'Ride or Die'],

    // ===== Brands/IP =====
    ['Spotify', 'Apple Music'],
    ['ChatGPT', 'Siri'],
    ['Tesla', 'Edison'],
    ['Amazon', 'Walmart'],
    ['Google', 'Bing'],
    ['Twitter/X', 'Threads'],
    ['Fortnite', 'Apex Legends'],
    ['Minecraft', 'Roblox'],
    ['Harry Potter', 'Lord of the Rings'],
    ['Batman', 'Iron Man'],
    ['Star Wars', 'Star Trek'],
    ['Disney', 'Pixar'],
    ['Starbucks', 'Dunkin'],
    ['Nike', 'Adidas'],
    ['PlayStation', 'Xbox'],

    // ===== Food =====
    ['Sushi', 'Sashimi'],
    ['Tacos', 'Burritos'],
    ['Ramen', 'Pho'],
    ['Croissant', 'Bagel'],
    ['Avocado Toast', 'Acai Bowl'],
    ['Mac and Cheese', 'Grilled Cheese'],
    ['Boba Tea', 'Iced Coffee'],
    ['Wings', 'Nuggets'],
    ['Fries', 'Onion Rings'],
    ['Cheesecake', 'Tiramisu'],

    // ===== Relationships/Social =====
    ['Ex', 'Current'],
    ['Long Distance', 'Online Dating'],
    ['Confession', 'Hint'],
    ['First Date', 'Blind Date'],
    ['Breakup Text', 'In Person Breakup'],
    ['DTR Talk', 'The Ick'],
    ['Slow Fade', 'Ghosting'],
    ['Talking Stage', 'Dating'],
    ['Rebound', 'The One'],
    ['Couples Therapy', 'Self Help Book'],
  ],

  ru: [
    // ===== EASY =====
    ['Кока-Кола', 'Пепси'],
    ['Пельмени', 'Вареники'],
    ['Баня', 'Сауна'],
    ['Квас', 'Компот'],
    ['Борщ', 'Щи'],
    ['Метро', 'Трамвай'],
    ['Кошка', 'Собака'],
    ['Зима', 'Осень'],
    ['Блины', 'Оладьи'],
    ['Гитара', 'Балалайка'],
    ['Вертолёт', 'Самолёт'],
    ['Зонт', 'Дождевик'],
    ['Мороженое', 'Эскимо'],
    ['Рюкзак', 'Чемодан'],
    ['Пингвин', 'Страус'],
    ['Крокодил', 'Акула'],
    ['Наушники', 'Колонка'],
    ['Духовка', 'Микроволновка'],
    ['Пароль', 'Ключ'],
    ['Фотоаппарат', 'Телескоп'],

    // ===== MEDIUM =====
    ['Дача', 'Деревня'],
    ['Студент', 'Школьник'],
    ['Экзамен', 'Зачёт'],
    ['Квартира', 'Дом'],
    ['Шаурма', 'Бургер'],
    ['Рубль', 'Доллар'],
    ['Снеговик', 'Дед Мороз'],
    ['Театр', 'Кино'],
    ['Балет', 'Танец'],
    ['Берёза', 'Дуб'],
    ['Империя', 'Республика'],
    ['Олигарх', 'Бизнесмен'],
    ['Танк', 'Трактор'],
    ['Матрёшка', 'Кукла'],
    ['Космонавт', 'Лётчик'],
    ['Икра', 'Рыба'],
    ['Мафия', 'Полиция'],
    ['Водка', 'Пиво'],
    ['Пушкин', 'Толстой'],
    ['Вампир', 'Зомби'],
    ['Шпион', 'Детектив'],
    ['Яд', 'Противоядие'],
    ['Замок', 'Дворец'],
    ['Хакер', 'Программист'],
    ['Тюрьма', 'Психбольница'],

    // ===== HARD =====
    ['Абьюз', 'Газлайтинг'],
    ['Токсик', 'Нарцисс'],
    ['Краш', 'Симп'],
    ['Рофл', 'Кринж'],
    ['Вайб', 'Атмосфера'],
    ['Хайп', 'Тренд'],
    ['Чилл', 'Релакс'],
    ['Зумер', 'Миллениал'],
    ['Кэнсел', 'Буллинг'],
    ['Флекс', 'Понты'],
    ['Рил', 'Тикток'],
    ['Шиппить', 'Фанатеть'],
    ['Краш', 'Бывший'],
    ['Стендап', 'Камеди'],
    ['Кешбэк', 'Скидка'],
    ['Каршеринг', 'Такси'],
    ['Маркетплейс', 'Магазин'],
    ['Нетфликс', 'Кинотеатр'],
    ['Блогер', 'Журналист'],
    ['Репост', 'Скриншот'],

    // ===== Brands/Culture =====
    ['Яндекс', 'Google'],
    ['VK', 'Telegram'],
    ['Озон', 'Wildberries'],
    ['Самокат', 'Яндекс Еда'],
    ['Сбер', 'Тинькофф'],
    ['iPhone', 'Samsung'],
    ['PlayStation', 'Xbox'],
    ['Dota', 'CS'],
    ['Minecraft', 'Roblox'],
    ['Гарри Поттер', 'Властелин Колец'],

    // ===== Food =====
    ['Шашлык', 'Кебаб'],
    ['Суши', 'Роллы'],
    ['Чебурек', 'Беляш'],
    ['Пирожок', 'Самса'],
    ['Лагман', 'Лапша'],
    ['Селёдка', 'Килька'],
    ['Сырники', 'Творожная запеканка'],
    ['Окрошка', 'Свекольник'],
    ['Пастила', 'Зефир'],
    ['Солянка', 'Рассольник'],

    // ===== Relationships/Social =====
    ['Бывший', 'Нынешний'],
    ['Свидание', 'Свиданка'],
    ['Признание', 'Намёк'],
    ['Френдзона', 'Игнор'],
    ['Лав-стори', 'Ромком'],
    ['Тиндер', 'Знакомство в баре'],
    ['Расставание', 'Пауза'],
    ['Ревность', 'Паранойя'],
    ['Комплимент', 'Подкат'],
    ['Токсичные отношения', 'Созависимость'],
  ],
};

/** Structured pairs with difficulty metadata (for future theme/difficulty selection) */
export const WORD_PAIRS_STRUCTURED: Record<string, WordPairEntry[]> = {
  zh: [
    // Easy
    ...WORD_PAIRS_BY_LANG.zh.slice(0, 20).map((pair) => ({ pair, difficulty: 'easy' as Difficulty, tags: ['general'] })),
    // Medium
    ...WORD_PAIRS_BY_LANG.zh.slice(20, 52).map((pair) => ({ pair, difficulty: 'medium' as Difficulty, tags: ['general'] })),
    // Hard
    ...WORD_PAIRS_BY_LANG.zh.slice(52, 73).map((pair) => ({ pair, difficulty: 'hard' as Difficulty, tags: ['slang'] })),
    // Brands
    ...WORD_PAIRS_BY_LANG.zh.slice(73, 93).map((pair) => ({ pair, difficulty: 'medium' as Difficulty, tags: ['brands'] })),
    // Food
    ...WORD_PAIRS_BY_LANG.zh.slice(93, 103).map((pair) => ({ pair, difficulty: 'medium' as Difficulty, tags: ['food'] })),
    // Romance
    ...WORD_PAIRS_BY_LANG.zh.slice(103, 113).map((pair) => ({ pair, difficulty: 'medium' as Difficulty, tags: ['romance'] })),
    // Work/School
    ...WORD_PAIRS_BY_LANG.zh.slice(113).map((pair) => ({ pair, difficulty: 'medium' as Difficulty, tags: ['work'] })),
  ],
};
